apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-app-chart.fullname" . }}
  labels:
    {{- include "node-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.TargetPort }}
      protocol: {{ .Values.service.protocols }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "node-app-chart.selectorLabels" . | nindent 4 }}
